name: Tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Test with coverage & unittest
      run: |
        pip install invoke
        pip install lib/aed_ds-0.0.2-py3-none-any.whl
        pip install coverage
        invoke cov
